// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/obsidian-lint/pkg/formatter"
	"github.com/bborbe/obsidian-lint/pkg/model"
)

type Formatter struct {
	FormatStub        func(context.Context, *model.ValidationResult) (string, error)
	formatMutex       sync.RWMutex
	formatArgsForCall []struct {
		arg1 context.Context
		arg2 *model.ValidationResult
	}
	formatReturns struct {
		result1 string
		result2 error
	}
	formatReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Formatter) Format(arg1 context.Context, arg2 *model.ValidationResult) (string, error) {
	fake.formatMutex.Lock()
	ret, specificReturn := fake.formatReturnsOnCall[len(fake.formatArgsForCall)]
	fake.formatArgsForCall = append(fake.formatArgsForCall, struct {
		arg1 context.Context
		arg2 *model.ValidationResult
	}{arg1, arg2})
	stub := fake.FormatStub
	fakeReturns := fake.formatReturns
	fake.recordInvocation("Format", []interface{}{arg1, arg2})
	fake.formatMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Formatter) FormatCallCount() int {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	return len(fake.formatArgsForCall)
}

func (fake *Formatter) FormatCalls(stub func(context.Context, *model.ValidationResult) (string, error)) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = stub
}

func (fake *Formatter) FormatArgsForCall(i int) (context.Context, *model.ValidationResult) {
	fake.formatMutex.RLock()
	defer fake.formatMutex.RUnlock()
	argsForCall := fake.formatArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Formatter) FormatReturns(result1 string, result2 error) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	fake.formatReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Formatter) FormatReturnsOnCall(i int, result1 string, result2 error) {
	fake.formatMutex.Lock()
	defer fake.formatMutex.Unlock()
	fake.FormatStub = nil
	if fake.formatReturnsOnCall == nil {
		fake.formatReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.formatReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Formatter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Formatter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ formatter.Formatter = new(Formatter)
