// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/obsidian-lint/pkg/index"
)

type IndexBuilder struct {
	BuildStub        func(context.Context, string, []string) (*index.VaultIndex, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}
	buildReturns struct {
		result1 *index.VaultIndex
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 *index.VaultIndex
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IndexBuilder) Build(arg1 context.Context, arg2 string, arg3 []string) (*index.VaultIndex, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2, arg3Copy})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IndexBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *IndexBuilder) BuildCalls(stub func(context.Context, string, []string) (*index.VaultIndex, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *IndexBuilder) BuildArgsForCall(i int) (context.Context, string, []string) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IndexBuilder) BuildReturns(result1 *index.VaultIndex, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 *index.VaultIndex
		result2 error
	}{result1, result2}
}

func (fake *IndexBuilder) BuildReturnsOnCall(i int, result1 *index.VaultIndex, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 *index.VaultIndex
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 *index.VaultIndex
		result2 error
	}{result1, result2}
}

func (fake *IndexBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IndexBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ index.Builder = new(IndexBuilder)
