// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/obsidian-lint/pkg/model"
	"github.com/bborbe/obsidian-lint/pkg/parser"
)

type Parser struct {
	ParseAliasesStub        func(context.Context, string) ([]string, error)
	parseAliasesMutex       sync.RWMutex
	parseAliasesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	parseAliasesReturns struct {
		result1 []string
		result2 error
	}
	parseAliasesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ParseFileStub        func(context.Context, string) ([]*model.Link, error)
	parseFileMutex       sync.RWMutex
	parseFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	parseFileReturns struct {
		result1 []*model.Link
		result2 error
	}
	parseFileReturnsOnCall map[int]struct {
		result1 []*model.Link
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Parser) ParseAliases(arg1 context.Context, arg2 string) ([]string, error) {
	fake.parseAliasesMutex.Lock()
	ret, specificReturn := fake.parseAliasesReturnsOnCall[len(fake.parseAliasesArgsForCall)]
	fake.parseAliasesArgsForCall = append(fake.parseAliasesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ParseAliasesStub
	fakeReturns := fake.parseAliasesReturns
	fake.recordInvocation("ParseAliases", []interface{}{arg1, arg2})
	fake.parseAliasesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Parser) ParseAliasesCallCount() int {
	fake.parseAliasesMutex.RLock()
	defer fake.parseAliasesMutex.RUnlock()
	return len(fake.parseAliasesArgsForCall)
}

func (fake *Parser) ParseAliasesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.parseAliasesMutex.Lock()
	defer fake.parseAliasesMutex.Unlock()
	fake.ParseAliasesStub = stub
}

func (fake *Parser) ParseAliasesArgsForCall(i int) (context.Context, string) {
	fake.parseAliasesMutex.RLock()
	defer fake.parseAliasesMutex.RUnlock()
	argsForCall := fake.parseAliasesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Parser) ParseAliasesReturns(result1 []string, result2 error) {
	fake.parseAliasesMutex.Lock()
	defer fake.parseAliasesMutex.Unlock()
	fake.ParseAliasesStub = nil
	fake.parseAliasesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *Parser) ParseAliasesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.parseAliasesMutex.Lock()
	defer fake.parseAliasesMutex.Unlock()
	fake.ParseAliasesStub = nil
	if fake.parseAliasesReturnsOnCall == nil {
		fake.parseAliasesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.parseAliasesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *Parser) ParseFile(arg1 context.Context, arg2 string) ([]*model.Link, error) {
	fake.parseFileMutex.Lock()
	ret, specificReturn := fake.parseFileReturnsOnCall[len(fake.parseFileArgsForCall)]
	fake.parseFileArgsForCall = append(fake.parseFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ParseFileStub
	fakeReturns := fake.parseFileReturns
	fake.recordInvocation("ParseFile", []interface{}{arg1, arg2})
	fake.parseFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Parser) ParseFileCallCount() int {
	fake.parseFileMutex.RLock()
	defer fake.parseFileMutex.RUnlock()
	return len(fake.parseFileArgsForCall)
}

func (fake *Parser) ParseFileCalls(stub func(context.Context, string) ([]*model.Link, error)) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = stub
}

func (fake *Parser) ParseFileArgsForCall(i int) (context.Context, string) {
	fake.parseFileMutex.RLock()
	defer fake.parseFileMutex.RUnlock()
	argsForCall := fake.parseFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Parser) ParseFileReturns(result1 []*model.Link, result2 error) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = nil
	fake.parseFileReturns = struct {
		result1 []*model.Link
		result2 error
	}{result1, result2}
}

func (fake *Parser) ParseFileReturnsOnCall(i int, result1 []*model.Link, result2 error) {
	fake.parseFileMutex.Lock()
	defer fake.parseFileMutex.Unlock()
	fake.ParseFileStub = nil
	if fake.parseFileReturnsOnCall == nil {
		fake.parseFileReturnsOnCall = make(map[int]struct {
			result1 []*model.Link
			result2 error
		})
	}
	fake.parseFileReturnsOnCall[i] = struct {
		result1 []*model.Link
		result2 error
	}{result1, result2}
}

func (fake *Parser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Parser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ parser.Parser = new(Parser)
